"""Lyric : champs artiste manuels

Revision ID: f57929575952
Revises: 931087bac51a
Create Date: 2026-09-25 16:20:07.106189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57929575952'
down_revision = '931087bac51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('artist_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('artist_photo', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_lyrics_artist_id'))
        batch_op.drop_constraint(batch_op.f('unique_song_per_artist'), type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_song_per_artist'), ['artist_id', 'song_title'])
        batch_op.create_index(batch_op.f('ix_lyrics_artist_id'), ['artist_id'], unique=False)
        batch_op.drop_column('artist_photo')
        batch_op.drop_column('artist_code')
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
